<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            $rules['title'] = 'required|unique:posts|min:3|max:100',
            'except' => 'required|min:100|max:200',
            'body' => 'required',
            'image' => 'mimes:jpeg,png|max:5000',
        ];
        if ($this->isMethod('PATCH')) {
            $rules['title'] = 'required|min:3|max:100';
        }
        return $rules;
    }
    public function messages()
    {
        return [
          'required'=>'Поле <<:attribute>> обязательно для заполнения',
          'unique'=>'Такое значение для поля <<:attribute>> уже используется',
          'min'=>[
              'string'=>'Поле <<:attribute>> должно быть не меньше :min символов',
              'file'=>'Файл <<:attribute>> должно быть не меньше :min Кбайт',
          ],
          'max'=>[
              'string'=>'Поле <<:attribute>> должно быть не больше :min символов',
              'file'=>'Файл <<:attribute>> должно быть не больше :min Кбайт',
          ],
          'mimes'=>'Файл <<:attribute>> должен имметь формат :values',
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
    public function attributes()
    {
        return [
          'title'=>'Заголовок',
          'except'=>'Анонс поста',
          'body'=>'Текст поста',
          'image'=>'Изображение',
        ];
//        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
