<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    public function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException) {
            abort(404);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

//    public function render(Request $request, Throwable $e)
//    {
//        if ($e instanceof ModelNotFoundException) {
//            abort(404);
//        }
//        return parent::render($request, $e); // TODO: Change the autogenerated stub
//    }

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
}
